poetry.lock
pyproject.toml

Pyyaml is downgraded from `6.0 -> 5.4.1` as ZenML requires `5.4.1`. 

[RPD-140] Downgrade pyyaml package

---

src/matcha_ml/cli/cli.py

This PR updates the doc links shown when the`matcha` command is run. Previously, matcha command points to https://docs.mlops.wtf which have now been replaced by https://fuzzylabs.github.io/matcha/.

[RPD-141] Update the documentation link for matcha cli

---

src/matcha_ml/cli/_validation.py
src/matcha_ml/cli/cli.py
src/matcha_ml/cli/provision.py
tests/test_cli/test_provision.py

Ask for provisioning variables only after checking if there's an existing configuration.
Do not ask for the variables, if the configuration exists, and the user tells to not override it. Allow for empty variables in validation, so we do not make the CLI options mandatory. Prompt and fill in the variables only if they were not provided as CLI options.

[RPD-132] Move `matcha provision` existing deployment validations to the start of the command

---

.github/workflows/docs.yml
src/matcha_ml/services/terraform_service.py
src/matcha_ml/templates/run_template.py
tests/test_services/test_terraform_service.py

An error occurs when `~/.kube/config` file is missing following error occurs.
```bash
MatchaTerraformError: Terraform failed because of the following error: '
Error: Get "http://localhost/api/v1/namespaces/default/services/mlflow-tracking": dial tcp 127.0.0.1:80: connect: connection refused
with module.mlflow.data.kubernetes_service.mlflow_tracking,
on mlflow_module/getURI.tf line 2, in data "kubernetes_service" "mlflow_tracking":
2: data "kubernetes_service" "mlflow_tracking" {
```
The solution: Create a `~/.kube/config` file if it does not exist before terraform apply.

[RPD-167] `provision` fails when run on the machine which has never done anything k8s related

---

src/matcha_ml/cli/_validation.py
src/matcha_ml/cli/cli.py
src/matcha_ml/cli/destroy.py
src/matcha_ml/infrastructure/main.tf
src/matcha_ml/templates/build_templates/azure_template.py
src/matcha_ml/templates/run_template.py
tests/test_cli/test_provision.py
tests/test_templates/test_azure_template.py
tests/test_templates/test_run_template.py

The bug appears to be because the `matcha.state` file hasn't been created so the `check_current_deployment_exists()` function is returning False when checking whether the file exists (see this [line](https://github.com/fuzzylabs/matcha/blob/8170c91b2a34b15398f3b04c7b929a4b02116400/src/matcha_ml/cli/_validation.py#L222)). This means that there's no way for the user to destroy the partially provisioned resources without manually going to the Azure console - we want to avoid this.
`check_current_deployment_exists()` function has been modified to look for name of resource group in two different ways. That way even if resource group is created and provision fails in between, we should be able to run `matcha destroy` command.
The previous behavior was, `matcha destroy` would raise a error that …

[RPD-171] unable to destroy when provision fails part way through

---

src/matcha_ml/templates/run_template.py
tests/test_templates/test_run_template.py

In this ticket, we create a unique identifier for state file. To do this, we update the contents matcha.state file  with new identifier of following structure.
```json
{
"orchestrator": {
"flavor": "aks",
"k8s-context": "k8s_test_context",
},
"container-registry": {
"flavor": "azure",
"registry-url": "azure_container_registry",
},
"id": {"matcha_uuid": "matcha_id_test_value"},
}
```
Here `id` field is added to exisiting dict with value `{"matcha_uuid": "matcha_id_test_value"}`. The `matcha_id_test_value` will consist of randomly generated UUID.

[RPD-169] Add unique identifier or ID to a state file

---

README.md

The image and GIF from the documentation [do not load on PyPi](https://pypi.org/project/matcha-ml/).
To fix this the image links that exist on the PyPi page are updated to the 'raw' links instead of the GitHub page e.g. for the GIF https://raw.githubusercontent.com/fuzzylabs/matcha/main/docs/img/matcha-provision.gif
NOTE: There may be better options for this as we are specifying the image existing on the main branch which could cause complications in the future when updating these images.
Docs fix

[RPD-181] Update README with raw links to images

---

src/matcha_ml/cli/analytics.py
tests/conftest.py
tests/test_cli/test_analytics.py

This pull request adds default functionality to the `analytics` command, such that the `--help` option will be displayed by default where no other options, arguments, or sub-commands are passed. This is implemented by using typer's built-in `no_args_is_help=True` argument when creating the analytics sub-command branch.
One additional test has been included to test this functionality.
This PR also corrects for missing type definitions in relevant functions and modules.

[RPD-183] Refactor `matcha analytics` command to display help when no argument passed

---

src/matcha_ml/cli/destroy.py
src/matcha_ml/cli/provision.py
src/matcha_ml/state/remote_state_manager.py
src/matcha_ml/storage/azure_storage.py
tests/test_cli/test_provision.py
tests/test_state/test_remote_state_manager.py

This pull request introduces a context manager that is used to download the state files from the remote storage before running `provision` or `destroy`, and upload files to the remote storage following the `provision` or `destroy` logic. The context manager uses the `contexlib` library and invokes `upload` and `download` from the `RemoteStateManager`.

[RPD-145] Get the state before `provision` or `destroy` command is run

---

src/matcha_ml/storage/azure_storage.py
tests/test_storage/test_azure_storage.py

The [download_folder](https://github.com/fuzzylabs/matcha/blob/develop/src/matcha_ml/storage/azure_storage.py#LL101C1-L113C1) function inside `azure_storage.py`  tires to delete all the files inside the directory passed as argument i.e. `dest_folder_path`. 
To fix the bug, we only delete the `.matcha` folder when both remote_storage and resources folders are present inside `.matcha`  folder. This will ensure, we are uploading and downloading same folders i.e. remote state bucket acts as a oracle.
Detailed explanation can be found in the ticket.

[RPD-229] [BUG] `download_folder` function tries to delete entire directory

---

src/matcha_ml/cli/cli.py
src/matcha_ml/cli/constants.py
src/matcha_ml/cli/destroy.py
src/matcha_ml/cli/provision.py
src/matcha_ml/runners/azure_runner.py
src/matcha_ml/runners/base_runner.py
src/matcha_ml/state/remote_state_manager.py
tests/test_runners/test_azure_runner.py
tests/test_runners/test_base_runner.py
tests/test_state/test_remote_state_manager.py

This pull request implements the following changes to the UI to account for the addition of remote state:
- Updates the console message once remote state resources have been provisioned.
- Differentiates the resources to be destroyed between `matcha destroy` and `matcha destroy full`.
- Adds a progress spinner for the `destroy` cli command.
- Adds a warning message relating to orphaned cloud assets on 'matcha destroy'.
- Updates the status message once remote state is destroyed.
This pull request was created to ensure that the UI messaging to the user remains relevant given the changes in provisioning and destroying infrastructure following the introduction of remote state.
Most of the changes have been achieved through changes to static messages, or through the reuse of UI components …

[RPD-231] Improvements to `provision` and `destroy` logging

---

src/matcha_ml/services/_validation.py
src/matcha_ml/services/analytics_service.py
src/matcha_ml/services/global_parameters_service.py
tests/test_services/__init__.py
tests/test_services/conftest.py
tests/test_services/test_analytics_service.py
tests/test_services/test_global_parameters_service.py
tests/test_services/test_validation.py

This PR introduces a validation check for the uuid's that we're generating (one for the user and one for the matcha environment). The check is simple, if the parsed ID can be used to create a `UUID` object then we know it's a valid UUID.
We're introducing this check as there's a possibly a user could inadvertently modify the two ids, which is something that want to avoid for obvious reasons.
If the potential uuid can be parsed as a UUID object, then the function returns `True`, otherwise an error is raised.
These checks have been added into the code where relevant and tests have been updated accordingly, more precisely:
* A `_check_uuid` function has been introduced in a new `_validation` file under `services`.
* Checks have been added to the `analytics_service` and …

[RPD-237] Add a check for the user and environment uuid

---

src/matcha_ml/cli/provision.py
src/matcha_ml/state/remote_state_manager.py
tests/test_cli/test_provision.py
tests/test_state/test_remote_state_manager.py

When a user deletes a resource group manually or uses a shared state and another person has run `matcha destroy full` the user would be left with an out-of-sync config file. This would cause errors when running `matcha provision` again as the specified resource group would not exist.
This PR aims to fix this by checking if the state is stale (the user has a remote state config file but the resource group does not exist) and based on the user's decision, either:
1. Removes the remote config file and continue with a new deployment
2. Or the user can stop the command at this point

[RPD-234] [BUG] Handle existing matcha configuration better

---

src/matcha_ml/cli/cli.py
src/matcha_ml/core/core.py
src/matcha_ml/state/matcha_state.py
src/matcha_ml/state/remote_state_manager.py
src/matcha_ml/storage/azure_storage.py
tests/test_cli/test_get.py
tests/test_core/test_core.py
tests/test_state/test_matcha_state.py

Instead of downloading `.matcha` folder everytime we run `matcha get` command as mentioned in architecture diagram. An efficient approach would be to compare the hash of contents of the local matcha state and remote matcha state, download the entire `.matcha` folder only if the hash is different.
In this PR, we implement this verification on local and remote matcha state files.
Time Comparisions for running `matcha get` command
- On `develop` branch, adding `use_remote_state()` [here](https://github.com/fuzzylabs/matcha/blob/develop/src/matcha_ml/cli/cli.py#L93) i.e. download `.matcha` from remote every time we run get command  ~ 30 secs
- On `develop` branch, reading the local `matcha.state`  ~ 5-8 sec
- Current branch, verifying hash and then reading local `matcha.state` ~ 6-8 sec …

[RPD-226] Download `.matcha` from remote state storage if state file hash mismatch state when `matcha get` command is run

---

src/matcha_ml/services/global_parameters_service.py
tests/test_services/test_global_parameters_service.py

This PR makes Matcha POSIX compliant. More specifically, the prior location of the global configuration file was in a `.matcha-ml` directory in the users home directory - this goes against POSIX principles. In this PR, that location is changed in the code to the `.config` directory in the home directory and `.matcha-ml` is no longer a hidden directory.

[RPD-233] Change the matcha-ml global variable config location from a users home folder

---

src/matcha_ml/constants.py
src/matcha_ml/state/remote_state_manager.py
src/matcha_ml/storage/azure_storage.py
tests/test_storage/test_azure_storage.py

After running provision a matcha.lock file is created in the users local directory. This is not meant to happen as the lock file is only meant to exist on the Azure blob storage.
This bug is due to the way we sync a user's local files with the Azure blob storage. When we sync and download the remote state, the matcha.lock file exists on Azure, hence we download that. To fix this we ignore `matcha.lock` on downloading.
Another bug exists where after `matcha provision` has completed, due to the `matcha.lock` file not existing within the user’s `.matcha` folder, the `matcha.lock` file is removed from the remote blob storage when syncing at the end of the provision command and the user is given the warning Tried unlocking state, but it was not locked. 
This is fixed by updating the …

[RPD-238] [BUG] Stop matcha.lock file from being created in the users local directory

---

src/matcha_ml/cli/cli.py
src/matcha_ml/runners/azure_runner.py
src/matcha_ml/runners/remote_state_runner.py
src/matcha_ml/services/terraform_service.py
tests/test_runners/test_azure_runner.py
tests/test_runners/test_remote_state_runner.py
tests/test_services/test_terraform_service.py

Consider  a scenario where one user has created the resources and other user is trying to destroy resource. This is currently not supported in matcha.
The issue arises as we are not uploading terraform cache stored inside .terraform folder. The other user will only download the terraform files and will not have `.terraform` folder. This folder is created using `terraform ini`t command or `_initialize_terraform` inside matcha.
We implement a fix in this PR by calling init function while destroying the resources for both `RemoteState` and `Azure` runners.

[RPD-240] `matcha destroy` command does not work in remote scenraio

---

.github/workflows/ci.yml

Currently, GitHub CI does not run on branches merging into feature branches. This pr fixes this by updating the CI from:
```
on:
workflow_call:
pull_request:
branches:
- main
- develop
push:
branches:
- main
- develop
```
to:
```
on:
workflow_call:
pull_request:
branches:
- main
- develop
- '**feature**'
push:
branches:
- main
- develop
- '**feature**'
```
Which will match any branch that contains the word feature at any position in the branch name. In the future, we may want to specify feature branches in a different way such as `feature/RPD-xxx-implement-xyz`

[RPD-244] Add CI to feature branches

---

src/matcha_ml/cli/cli.py
src/matcha_ml/core/__init__.py
tests/test_cli/test_analytics.py
tests/test_cli/test_force_unlock.py
tests/test_core/test_core.py

Currently, the imports from the `core` module are convoluted. To fix this we add the functions to an `init` file within the `core` directory and update the imports accordingly. 
This also means if a user wants to run this in an API session they can simply use the command:
```
import matcha_ml.core as matcha
matcha.provision(...)
matcha.get(...)
...
```

[RPD-191] Add an init to core to enable a cleaner import

---

src/matcha_ml/cli/destroy.py
src/matcha_ml/cli/provision.py
src/matcha_ml/cli/ui/functions.py
src/matcha_ml/cli/ui/user_approval_functions.py
src/matcha_ml/runners/azure_runner.py
tests/test_cli/test_ui_functions.py
tests/test_runners/test_azure_runner.py

This pull request refactors the `is_approved` logic, which is currently a method of the `runners.azure_runner.AzureRunner` class, into a separate module within the `cli.ui` submodule.  The logic of the function is unchanged; imports and references have been updated to reflect the new location.

[RPD-193] Refactor `TemplateRunner.is_approved` into a UI function

---

src/matcha_ml/core/core.py
tests/test_core/test_core.py

Currently, when a user does not have a `.matcha` file locally that is not up to date with the remote state the user will encounter an error when trying to run `matcha get` to download/sync the state files.
This PR adds a test describing this bug and fixes it by calling the class method to check if the state file exists before instantiating the object `MatchaStateService` and then instantiating after the check and download remote state has completed.

[BUG] [RPD-258] Instantiate MatchStateService after downloading the matcha state from the remote storage

---

src/matcha_ml/core/core.py

This is a very small PR which extends the `destroy()`, `get()` and `provision()` docstrings slightly, such that the API docs are more easily followed.
Docs improvement

[RPD-255] improve docstrings in core module

---

src/matcha_ml/services/analytics_service.py

This PR patches over the issue of tracking destruction events leading to errors. 
This is done by having two conditionals which check the type of analytic event being tracked, and executing the call to the associated function in the appropriate place inside the track decorator. 
This is only a temporary fix and will be entirely removed by the imminent re-writing of the track decorator. This will remain a draft until I have successfully ran the entire pipeline without issue tomorrow.

[RPD-254] no state file after destroying resources

---

src/matcha_ml/core/core.py
src/matcha_ml/state/remote_state_manager.py
tests/test_state/test_remote_state_manager.py

The error is due to the context managers `use_remote_state` and `use_lock`. These both call functions dependent on the Azure bucket existing: `unlock` and `upload`. To fix this we updated context managers to avoid erroring on destroy after the remote bucket is removed by introducing a `destroy` variable which prevents these two functions from being run on a `destroy` command.

[RPD-261] [BUG] destroy leads to missing matcha config file error

---

docs/azure-permissions.md
docs/getting-started.md

There are a few minor improvements that can be made to the documentation:
**Getting Started**
References to the `full` command don't appear in the documentation.
**Azure Permissions**
**Deploying your first model**
The language is clear enough as training is stated throughout the page and it's about getting started with deploying more generally so I don't think this change needs to be made.

[RPD-272] Updates to documentation

---

src/matcha_ml/services/analytics_service.py
tests/conftest.py

This bug was caused by local networks not allowing access to the Segment server. This bug can be recreated by adding `127.0.0.1    api.segment.io` to `/etc/hosts`. And running any `matcha` command that has a `track` decorator.
To fix this we set the Segment max tries to 1 and suppress Segment logging output.
This also fixes issue RPD-262

[RPD-276] [BUG] Turning analytics `on` causes hanging in the analytics service

---

docs/getting-started.md
docs/inside-matcha.md

This was reported as a bug, however, it's actually a feature. The `NetworkWatcherRG` is a resource group that is automatically provisioned by Azure when:
1. A resource has in-coming traffic; AND,
2. When a `NetworkWatcherRG` doesn't already exist in the region for the subscription.
This sits at a higher level than Matcha, and isn't controlled by the tool. 
This PR adds clarifying statements to the documentation, pointing to information on Azure.

[RPD-271] [BUG] Fix orphaned `NetworkWatcherRG` resource group

---

src/matcha_ml/infrastructure/remote_state_storage/output.tf
src/matcha_ml/state/matcha_state.py
src/matcha_ml/templates/azure_template.py

This bug is recreated by allowing the state storage to be provisioned and stopping the program before reaching the AKS and other resources provisioning. This meant that the `matcha.state` file looks similar to:
```
{
"cloud": {
"prefix": "test",
"location": "uksouth",
}
}
```
Which does not include `resource-group-name` hence when we try to access this value to check if the matcha state is stale
we get an error that the value does not exist.
Instead the `matcha.state` file needs to be:
```
{
"cloud": {
"prefix": "test",
"location": "uksouth",
"resource-group-name": "test-resources"
}
}
```
After the resource group and state storage is provisioned.
This bug can happen if there is something wrong with the `resources` Terraform and the Terraform init/apply fails causing matcha to halt …

[RPD-279] [BUG] Automatically deal with stale states 

---

src/matcha_ml/runners/azure_runner.py

RESOURCE_NAMES variable not used in azure_runner.py so has been removed. No need to move to constants.py.

RPD-280 remove RESOURCE_NAMES from azure_runner

---

src/matcha_ml/infrastructure/resources/data_version_control_storage/README.md
src/matcha_ml/infrastructure/resources/data_version_control_storage/main.tf
src/matcha_ml/infrastructure/resources/data_version_control_storage/output.tf
src/matcha_ml/infrastructure/resources/data_version_control_storage/providers.tf
src/matcha_ml/infrastructure/resources/data_version_control_storage/variables.tf
src/matcha_ml/infrastructure/resources/main.tf
src/matcha_ml/infrastructure/resources/output.tf

This PR adds the terraform files to the infrastructure directory for creating resources for storing and versioning data in future.
Add a data_version_control_storage/ directory to the infrastructure/ folder. Create an azurerm_storage_account resource and an azurerm_storage_container resource:
```
resource "azurerm_storage_account" "storageaccount" {
name                = "${var.prefix}dvcacc"
resource_group_name = var.resource_group_name
location            = var.location
account_tier                    = "Standard"
account_kind                    = "StorageV2"
account_replication_type        = "LRS"
enable_https_traffic_only       = true
access_tier                     = "Hot"
allow_nested_items_to_be_public = true
}
resource "azurerm_storage_container" "storagecontainer" {
name …
```

[RPD-205] add data versioning terraform files to infrastructure

---

src/matcha_ml/runners/azure_runner.py
src/matcha_ml/runners/base_runner.py
src/matcha_ml/runners/remote_state_runner.py
tests/test_runners/test_base_runner.py

This PR updates some misleading and inaccurate messages displayed by Matcha when Terraform apply has finished for both the remote state and general resources.

[RPD-274] [BUG] Fix inaccurate provisioning messages

---

src/matcha_ml/core/core.py

This PR adds code which checks the zenml version of the environment from which matcha is run. If it is not the expected version, a warning is shown at the start of the provisioning workflow but the user can continue. If no zenml is found locally, again the user can continue and a warning is shown at the start of the provisioning workflow.

[RPD-263] add inference of zenml version from environment

---

.github/workflows/ci.yml
src/matcha_ml/core/core.py
src/matcha_ml/infrastructure/resources/.terraform.lock.hcl
src/matcha_ml/infrastructure/resources/main.tf
src/matcha_ml/infrastructure/resources/variables.tf
src/matcha_ml/infrastructure/resources/zen_server/main.tf
src/matcha_ml/infrastructure/resources/zen_server/variables.tf
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/Chart.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-deployment.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-ingress.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/values.yaml
tests/test_cli/test_provision.py
tests/test_core/test_core_provision.py

This PR has matcha look for a local install of zenml in the environment from which it was launched, then sets the version to be installed on the remote resources accordingly. If no installation is found, then the most recent release of zen server is installed instead.
Most of the changes are to terraform files, where a new variable has been introduced. On the python side, the version is passed to `build_template_configuration` after it is inferred by new `infer_zenml_version` function. This function also prints to the terminal information regarding the selected zenml version.

[RPD-287] ZenML version inference for zenserver

---

poetry.lock
src/matcha_ml/config/__init__.py
src/matcha_ml/config/matcha_config.py
src/matcha_ml/core/core.py
src/matcha_ml/state/remote_state_manager.py
tests/conftest.py
tests/test_config/test_matcha_config.py
tests/test_state/test_remote_state_manager.py

This PR introduces a new module `matcha_config.py` to store the classes and services associated with the `matcha.config.json` file. This PR introduces an object representation of the `matcha.config.json` file, alongside a service class for interacting with the `MatchaConfig` object.
The service class implements two methods currently needed for interacting with the `matcha.config.json` file; `read_matcha_config`, for reading in data from the config JSON; and `delete_matcha_config`, for removing the config file.

[RPD-260] Add an object to handle the `matcha.config.json` file.

---

.github/workflows/ci.yml
poetry.lock
src/matcha_ml/cli/cli.py
src/matcha_ml/config/__init__.py
src/matcha_ml/config/matcha_config.py
src/matcha_ml/core/core.py
src/matcha_ml/infrastructure/resources/.terraform.lock.hcl
src/matcha_ml/infrastructure/resources/main.tf
src/matcha_ml/infrastructure/resources/variables.tf
src/matcha_ml/infrastructure/resources/zen_server/main.tf
src/matcha_ml/infrastructure/resources/zen_server/variables.tf
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/Chart.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-deployment.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-ingress.yaml
src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/values.yaml
src/matcha_ml/state/remote_state_manager.py
tests/conftest.py
tests/test_cli/test_provision.py
tests/test_cli/test_stack.py
tests/test_config/test_matcha_config.py
tests/test_core/test_core_provision.py
tests/test_core/test_stack_set.py
tests/test_state/test_remote_state_manager.py

This PR fills out the existing placeholder function in core.py for setting the stack to one of LLM or DEFAULT. It uses the new MatchaConfig and MatchaConfigService functionality.
The Stack name is verified with an Enum, and an EnumMeta class is included for quality of life and more readable code down the line. 
If the stack type specified doesn't exist in the Enum an error is thrown.
The expected behaviour from this PR is, if a config file exists already:
`$ matcha stack set llm`
The `matcha.config.json` file will look like this:
`{other_old_keys: other_old_values, stack: {"name": "LLM"}`,
and if it does not exist, the new one will simply look like this:
`{"stack": {"name": "LLM"}}`

[RPD-283] add core function for updating stack type

---

src/matcha_ml/core/core.py
src/matcha_ml/runners/azure_runner.py
src/matcha_ml/runners/base_runner.py
tests/test_cli/conftest.py
tests/test_cli/test_provision.py
tests/test_core/conftest.py
tests/test_core/test_core_provision.py
tests/test_runners/test_azure_runner.py

This PR moves the `_show_terraform_outputs` function out of the `azure_runner` class and into the `matcha_ml.core.core.py` module. The `_show_terraform_outputs` function is a generic utility function for the core `provision` function and, as such, should be contained in the same module. The return value of the `azure_runner`'s `provision` method has been updated to pass a `MatchaStateService` instance, instantiated with the terraform outputs of the provisioning` back to the core `provision` function.
A test has been added for the `_show_terraform_outputs` function.

[RPD-250] Move `_show_terraform_outputs()` into `provision`

---

src/matcha_ml/services/analytics_service.py
src/matcha_ml/state/matcha_state.py
tests/test_state/test_matcha_state.py

This PR refactors the `build_state_from_terraform_output` method to make use of the custom classes within the `matcha_state.py` module. 
Previously, the `build_state_from_terraform_output` method made use of the `_parse_terraform_output` utility function to build a dictionary representation of state. This dictionary was then converted into a `MatchaState` object using the `from_dict` method in the MatchaState class.
In this new implementation, the `MatchaState` object is built using the relevant classes representing underlying resources, properties and components.
This PR also updates the `get_component` method of the MatchaStateService by moving it to the `MatchaState` object and adding an ability for the method to return `None`. Changes have been made to the broader matcha codebase to …

[RPD-259] Refactor `build_state_from_terraform_output` within `matcha_state.py` to use objects defined within matcha_state.py

---

src/matcha_ml/config/matcha_config.py
tests/test_config/test_matcha_config.py

This PR updates the `find_component` method of the `MatchaConfig` object. Previously, for object representations of state or configuration, the relevant 'find component' method would throw an error if a relevant component could not be found. It was decided that the preferred behaviour would be to return a None value in those instances where a relevant component could not be found.
This PR updates the `find_component` method of the `MatchaConfig` object to return `None` in the event that a relevant component is not found. This PR also adds tests to cover this altered behaviour.

[RPD-290] Update MatchaConfig object to not throw an error when a matching property/component is not found

---

src/matcha_ml/core/core.py
src/matcha_ml/templates/azure_template.py
tests/test_cli/test_provision.py
tests/test_core/test_core_provision.py

This PR updates the `azure_template` and `core` modules to dynamically pass lists of components to the template builder depending on which stack has been set by the user.
Currently, the template builder is passed a list of components represented by a constant variable. This PR splits this constant variable into different stacks, which are passed to the template builder depending on what value the user's set stack takes.

[RPD-292] [BUG] Update AzureTemplate to not create redundant folders during provisioning

---

src/matcha_ml/core/core.py

The docstring for the `stack_set` core function was missing two components:
1. An example on how to use the function
2. The errors that are raised by the function
Both of these have been added as it's important information for the user.

[RPD-303] Update `stack_set` docstring to include example and raises

---

docs/getting-started.md
scratch.py

This PR updates the Matcha documentation to demonstrate an alternative API implementation for the `matcha-examples` repo.

[RPD-248] Add a basic example demonstrating how to use the API

---

src/matcha_ml/runners/base_runner.py
tests/test_runners/test_base_runner.py

Remove import of MatchaStateService, make provision and deprovision in BaseRunner abstract methods.

[RPD-305] fix circular import error

---

src/matcha_ml/cli/cli.py
src/matcha_ml/cli/constants.py
src/matcha_ml/cli/ui/user_approval_functions.py
src/matcha_ml/runners/base_runner.py
tests/test_cli/test_provision.py
tests/test_cli/test_ui_functions.py
tests/test_runners/test_base_runner.py

Update stack message based on the chosen predefined stack type

[RPD-291] Dynamically update provisioning message based on stack type
